name: Docker Image CI

on:
  push:
    branches: 
      - main
      - 'features/**'
  pull_request:
    branches:
      - main
      - 'features/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        #registry: # optional
        # Username used to log against the Docker registry
        username: msaldivar
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASS }}
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Build and push Docker images
      if: ${{ github.head_ref == 'master' }}
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: msaldivar/flask-app:$(date +%s)
